/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kpuig.flashycards;

import com.kpuig.flashycards.ui.MainApplication;

import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        Application.launch(MainApplication.class, args);
    }
}
